INSERT INTO STUDENT VALUES (1,20, 'Jack', 'Reacher', 'ECE');
INSERT INTO STUDENT VALUES (2,22, 'John', 'Lock', 'CE');
INSERT INTO STUDENT VALUES (3,20, 'Kate', 'Austen', 'ME');
INSERT INTO STUDENT VALUES (4,22, 'James', 'Ford', 'EE');
INSERT INTO STUDENT VALUES (5,24, 'Boon', 'Carlyle', 'CSE');